id: opecha:P004190
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD105840
  title: གོ་ར་ཚྭ་རྫོང་།
  volume: ''
  author: ''
  volumes:
    52ae846951574ba2806d0c70f914a693:
      image_group_id: I1PD105842
      title: ''
      volume_number: 1
      total_pages: 762
